# Generated by Django 5.1.2 on 2024-10-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotaluser",
            options={},
        ),
        migrations.AlterModelOptions(
            name="hotalvendor",
            options={},
        ),
        migrations.AlterModelTable(
            name="hotaluser",
            table="hotal_user",
        ),
        migrations.AlterModelTable(
            name="hotalvendor",
            table="hotal_vendor",
        ),
    ]
